export const SNACKBAR_DISPLAY = 'SNACKBAR_DISPLAY';
export const SNACKBAR_CLEAR = 'SNACKBAR_CLEAR';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';
